name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to Server
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USERNAME }}
          PASS: ${{ secrets.SERVER_PASSWORD }}
          SOURCE: ${{ secrets.DEPLOY_SOURCE }}
          TARGET: ${{ secrets.DEPLOY_TARGET }}
        run: |
          sshpass -p "$PASS" scp -o StrictHostKeyChecking=no -r $SOURCE $USER@$HOST:$TARGET
